DROP DATABASE IF EXISTS prueba;
CREATE DATABASE prueba;


CREATE TABLE Usuarios (
    UID SERIAL PRIMARY KEY,
    Nombre VARCHAR(255) UNIQUE NOT NULL,
    Correo VARCHAR(255) UNIQUE NOT NULL,
    Pass VARCHAR(255) NOT NULL
);

CREATE TABLE Rol (
    Rnombre VARCHAR(100) PRIMARY KEY,
    Mover BOOLEAN DEFAULT FALSE,
    Escribir BOOLEAN DEFAULT FALSE,
    Permisos_AD BOOLEAN DEFAULT FALSE
);

CREATE TABLE Diagrama (
    DID SERIAL PRIMARY KEY,
    Dnombre VARCHAR(150) NOT NULL,
    Color VARCHAR(20) DEFAULT 'gray'
);

CREATE TABLE Invitacion (
    IID SERIAL PRIMARY KEY,
    Mensaje TEXT DEFAULT '',
    Rol VARCHAR(100),
    CONSTRAINT fk_invitacion_rol FOREIGN KEY (Rol) REFERENCES Rol(Rnombre) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Registro_invitaciones (
    IID INT NOT NULL,
    DID INT NOT NULL,
    UID INT NOT NULL,
    PRIMARY KEY(DID, UID),
    CONSTRAINT fk_Rinvitacion_diagrama_Invitacion FOREIGN KEY (IID) REFERENCES Invitacion(IID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_Rinvitacion_diagrama_Diagrama FOREIGN KEY (DID) REFERENCES Diagrama(DID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_Rinvitacion_diagrama_USER FOREIGN KEY (UID) REFERENCES Usuarios(UID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Mensaje (
    MID SERIAL PRIMARY KEY,
    DID INT NOT NULL,
    Contenido TEXT,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Emisor VARCHAR(255),
    CONSTRAINT fk_mensaje_diagrama FOREIGN KEY (DID) REFERENCES Diagrama(DID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Columna (
    CID SERIAL PRIMARY KEY,
    Orden INT DEFAULT NULL,
    DID INT NOT NULL,
    Cnombre VARCHAR(100) NOT NULL,
    Color VARCHAR(20) DEFAULT 'gray',
    CONSTRAINT fk_columna_diagrama FOREIGN KEY (DID) REFERENCES Diagrama(DID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Participacion (
    DID INT NOT NULL,
    UID INT NOT NULL,
    Rnombre VARCHAR(100) NOT NULL DEFAULT 'Espectador',
    es_favorito BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (DID, UID),
    CONSTRAINT fk_part_diagrama FOREIGN KEY (DID) REFERENCES Diagrama(DID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_rt_usuario FOREIGN KEY (UID) REFERENCES Usuarios(UID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_part_rol FOREIGN KEY (Rnombre) REFERENCES Rol(Rnombre) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE Tarjeta (
    TID SERIAL PRIMARY KEY,
    CID INT NOT NULL,
    Titulo VARCHAR(200) NOT NULL,
    Contenido TEXT DEFAULT '',
    CONSTRAINT fk_tarjeta_pertenece_a_columna FOREIGN KEY (CID) REFERENCES Columna(CID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO Rol (Rnombre, Mover, Escribir, Permisos_AD) VALUES
('Espectador', FALSE, FALSE, FALSE),
('Colaborador', TRUE, TRUE, FALSE),
('Administrador', TRUE, TRUE, TRUE);

